<a href="https://colab.research.google.com/github/vikrampal12345/Resume_Analyser_Job_recommendation_Research/blob/main/02_Linear_model_training/2_Linear_model_training_resume.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("/content/annotated_resume.csv")

df.shape

(3890, 19)

In [ ]:
df.head()

,dataset_index,filename,file_path,resume_text,skills,education,experience_years,projects,certifications,job_role_1,confidence_1,job_role_2,confidence_2,job_role_3,confidence_3,job_role_4,confidence_4,job_role_5,confidence_5
0,0,Image_10.png,Resumes Datasets\Bing_images\Accountant resume...,NaN,"['QuickBooks', 'MS Office', 'ERP (SAP & Oracle...",MBA,8,[],"['Certified Management Accountant (CMA)', 'Cer...",Financial Controller,95,Accounting Manager,90,Finance Manager,85,Compliance Officer,80,Accountant,75
1,1,Image_11.jpg,Resumes Datasets\Bing_images\Accountant resume...,HOWARD GERRARD Accountant WORK EXPERIENCE Dyrp...,"['Accounting', 'Financial Accounting', 'VAT Re...",Bachelor of Commerce,12,[],[],Accountant,100,Financial Accountant,95,Budget Analyst,85,Cash Manager,80,Financial Controller,70
2,3,Image_14.jpg,Resumes Datasets\Bing_images\Accountant resume...,"Olivia Ogilvy, Accountant 1515 Pacific Ave, Lo...","['Financial Reporting', 'Accounting', 'Reconci...",MBA,7,[],['Chartered Financial Analyst (CFA)'],Accountant,100,Financial Analyst,90,Accounting Manager,80,Finance Manager,70,Financial Controller,60
3,4,Image_16.jpg,Resumes Datasets\Bing_images\Accountant resume...,Brooklyn NY (123) 456-7890 stephen@beamjobs co...,"['QuickBooks', 'Taxjar', 'GAAP accounting prin...",MBA Accounting,9,[],['Certified Public Accountant (CPA)'],Accountant,100,Financial Controller,90,Accounting Manager,80,Finance Manager,70,Senior Accountant,100
4,5,Image_17.jpg,Resumes Datasets\Bing_images\Accountant resume...,Marie Anderson Sometown; CO 55555 555.555.5555...,"['QuickBooks', 'SQL', 'SAP', 'Oracle', 'GAAP',...",Bachelor of Science in Accounting,10,[{'name': 'Tech Startup Accounting System Impl...,[],Accountant,100,Financial Analyst,90,Audit Specialist,85,Tax Accountant,80,Compliance Officer,75

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['resume_text'].duplicated().sum()

np.int64(624)

In [ ]:
df = df.drop_duplicates(subset="resume_text", keep="first")

In [ ]:
df.shape

(3266, 19)

In [ ]:
df.isnull().mean() * 100

dataset_index       0.000000
filename            0.000000
file_path           0.000000
resume_text         0.030618
skills              0.000000
education           0.000000
experience_years    0.000000
projects            0.000000
certifications      0.000000
job_role_1          0.000000
confidence_1        0.000000
job_role_2          0.000000
confidence_2        0.000000
job_role_3          0.000000
confidence_3        0.000000
job_role_4          0.000000
confidence_4        0.000000
job_role_5          0.000000
confidence_5        0.000000
dtype: float64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().mean() * 100

dataset_index       0.0
filename            0.0
file_path           0.0
resume_text         0.0
skills              0.0
education           0.0
experience_years    0.0
projects            0.0
certifications      0.0
job_role_1          0.0
confidence_1        0.0
job_role_2          0.0
confidence_2        0.0
job_role_3          0.0
confidence_3        0.0
job_role_4          0.0
confidence_4        0.0
job_role_5          0.0
confidence_5        0.0
dtype: float64

In [ ]:
df.shape

(3265, 19)

In [ ]:
df.to_csv('final_resume.csv')

In [ ]:
df.head(5)

,dataset_index,filename,file_path,resume_text,skills,education,experience_years,projects,certifications,job_role_1,confidence_1,job_role_2,confidence_2,job_role_3,confidence_3,job_role_4,confidence_4,job_role_5,confidence_5
1,1,Image_11.jpg,Resumes Datasets\Bing_images\Accountant resume...,HOWARD GERRARD Accountant WORK EXPERIENCE Dyrp...,"['Accounting', 'Financial Accounting', 'VAT Re...",Bachelor of Commerce,12,[],[],Accountant,100,Financial Accountant,95,Budget Analyst,85,Cash Manager,80,Financial Controller,70
2,3,Image_14.jpg,Resumes Datasets\Bing_images\Accountant resume...,"Olivia Ogilvy, Accountant 1515 Pacific Ave, Lo...","['Financial Reporting', 'Accounting', 'Reconci...",MBA,7,[],['Chartered Financial Analyst (CFA)'],Accountant,100,Financial Analyst,90,Accounting Manager,80,Finance Manager,70,Financial Controller,60
3,4,Image_16.jpg,Resumes Datasets\Bing_images\Accountant resume...,Brooklyn NY (123) 456-7890 stephen@beamjobs co...,"['QuickBooks', 'Taxjar', 'GAAP accounting prin...",MBA Accounting,9,[],['Certified Public Accountant (CPA)'],Accountant,100,Financial Controller,90,Accounting Manager,80,Finance Manager,70,Senior Accountant,100
4,5,Image_17.jpg,Resumes Datasets\Bing_images\Accountant resume...,Marie Anderson Sometown; CO 55555 555.555.5555...,"['QuickBooks', 'SQL', 'SAP', 'Oracle', 'GAAP',...",Bachelor of Science in Accounting,10,[{'name': 'Tech Startup Accounting System Impl...,[],Accountant,100,Financial Analyst,90,Audit Specialist,85,Tax Accountant,80,Compliance Officer,75
5,7,Image_19.png,Resumes Datasets\Bing_images\Accountant resume...,anna@novoresumecom Anna Gunther Senior Account...,"['Accounting', 'Financial Reporting', 'Cost Co...",Senior Accountant,10,[],['Certified Public Accountant'],Accountant,100,Financial Accountant,95,Accounting Manager,85,Finance Analyst,80,Financial Controller,70

In [ ]:
df = df.iloc[:,3:]

In [ ]:
df.head()

,resume_text,skills,education,experience_years,projects,certifications,job_role_1,confidence_1,job_role_2,confidence_2,job_role_3,confidence_3,job_role_4,confidence_4,job_role_5,confidence_5
1,HOWARD GERRARD Accountant WORK EXPERIENCE Dyrp...,"['Accounting', 'Financial Accounting', 'VAT Re...",Bachelor of Commerce,12,[],[],Accountant,100,Financial Accountant,95,Budget Analyst,85,Cash Manager,80,Financial Controller,70
2,"Olivia Ogilvy, Accountant 1515 Pacific Ave, Lo...","['Financial Reporting', 'Accounting', 'Reconci...",MBA,7,[],['Chartered Financial Analyst (CFA)'],Accountant,100,Financial Analyst,90,Accounting Manager,80,Finance Manager,70,Financial Controller,60
3,Brooklyn NY (123) 456-7890 stephen@beamjobs co...,"['QuickBooks', 'Taxjar', 'GAAP accounting prin...",MBA Accounting,9,[],['Certified Public Accountant (CPA)'],Accountant,100,Financial Controller,90,Accounting Manager,80,Finance Manager,70,Senior Accountant,100
4,Marie Anderson Sometown; CO 55555 555.555.5555...,"['QuickBooks', 'SQL', 'SAP', 'Oracle', 'GAAP',...",Bachelor of Science in Accounting,10,[{'name': 'Tech Startup Accounting System Impl...,[],Accountant,100,Financial Analyst,90,Audit Specialist,85,Tax Accountant,80,Compliance Officer,75
5,anna@novoresumecom Anna Gunther Senior Account...,"['Accounting', 'Financial Reporting', 'Cost Co...",Senior Accountant,10,[],['Certified Public Accountant'],Accountant,100,Financial Accountant,95,Accounting Manager,85,Finance Analyst,80,Financial Controller,70

In [ ]:
df['resume_text'][1]

"HOWARD GERRARD Accountant WORK EXPERIENCE Dyrpj.com Birmur=7M Cotpan LCCOUNTENT Locion PterenT 047b 467320 Re-ponsib Ujdzting znnun 7F mootr Tun-eg Dfine accOLTE dejirmert_ Iinbarc Director ireruliabe- contemtadutirtoices tnanosimatter info@cetjc?_ Leeping tinanciz contto econde eipe ndi-ure- OemeNt recciptz ralidiz , ccuno JrC CoT Zeres Minkeriauname Ventyine Ii702 oocumentz Managingthe receipts Ceporc Cashand banktnngacjons Erzunnb Ma Iryderande_RetJucitr7 pid #ccJiE y. SUMMARY Hovard corsideteg expert aMaraeine company Iinterarc Ijonsaterit accounidedable jemo-m Tarnemaje Giqulatonsuth Cotpank nam ACCOUNTENT Locaton Haintaininfthe qualiz' cijinanciz cntro , Organisin ~ordinainethework of accolndo Eeronnel Locjinz emors icounting record; Alonscollezzues other depanmengMin repantionoftheanr budzet; -pezdasWel eccuncan Can EZ relied upon provioe acclrate and truttrorny Trtonator TrarcAi [TPlementinp depannentz accojnmnf jolioez ProcedLTe-ird jrocere Urirg Tinanciai tooland ecnnique_ Evaluzte DLAne - OpPO ILJI8E3. Prezentire trountrs dazinaclear andundertancab Manrer tantactions EnTh ccnndentan Itatesic coleinany bujine ? Cotpank Nane 2015 ECCOUNTENT Locaton Pevevar monthk dejirtment Profit and Loxe; Aszistirz ninirox and _ juditz Detectirg enjnfTralt Contolling income anC aujenotur EDUCATION Dooutentin InEeTa ninaroa cOrtol Jroducirg detailed expendi-ure ejong_ Completing VAT retum Writirg cheque settirg BACS piTents_ Wntirs Izne cnecler tor_upplezaro ettire BACS pay Tents for Givine JenidnalaccountingiCYIcE Tholeero Univenihi 2010- 2013 Ioumedetai Mlodulez More te1 Cotpany 2013 - LCCOUNTENT Loczton Re-ponsib draftirs eponer cuener(n rerpec 0t -ubmized accolrors co TPietiong Cezurs Ipemenbrgird Tonhonrs Itan DonurecNete College Z0O8 - 2010 Courze detail: Sjiect More tet Scnool 2003- Z008 Courzc detail; SKILLS Accound 4*** Supervisin; **** ` WTTerurDE ** English (41 Maths Al dtd I + Physics Gedenaony ID Aepo= Payto _"

In [ ]:
import re
cleaned_resumes = []

for resume in df['resume_text']:
    lis = resume.replace(",", "").replace("/", "").replace('.', '').replace('(', '').replace('-', '').replace(')', '').replace('_', '').lower().split()
    lis = [word for word in lis if not word.isdigit()]
    obj = list(dict.fromkeys(lis))
    jo = " ".join(obj)
    cleaned_resumes.append(jo)

df['resume_text'] = cleaned_resumes

In [ ]:
df

,resume_text,skills,education,experience_years,projects,certifications,job_role_1,confidence_1,job_role_2,confidence_2,job_role_3,confidence_3,job_role_4,confidence_4,job_role_5,confidence_5
1,howard gerrard accountant work experience dyrp...,"['Accounting', 'Financial Accounting', 'VAT Re...",Bachelor of Commerce,12,[],[],Accountant,100,Financial Accountant,95,Budget Analyst,85,Cash Manager,80,Financial Controller,70
2,olivia ogilvy accountant pacific ave los angel...,"['Financial Reporting', 'Accounting', 'Reconci...",MBA,7,[],['Chartered Financial Analyst (CFA)'],Accountant,100,Financial Analyst,90,Accounting Manager,80,Finance Manager,70,Financial Controller,60
3,brooklyn ny stephen@beamjobs com linkedin step...,"['QuickBooks', 'Taxjar', 'GAAP accounting prin...",MBA Accounting,9,[],['Certified Public Accountant (CPA)'],Accountant,100,Financial Controller,90,Accounting Manager,80,Finance Manager,70,Senior Accountant,100
4,marie anderson sometown; co mac @somedomain co...,"['QuickBooks', 'SQL', 'SAP', 'Oracle', 'GAAP',...",Bachelor of Science in Accounting,10,[{'name': 'Tech Startup Accounting System Impl...,[],Accountant,100,Financial Analyst,90,Audit Specialist,85,Tax Accountant,80,Compliance Officer,75
5,anna@novoresumecom anna gunther senior account...,"['Accounting', 'Financial Reporting', 'Cost Co...",Senior Accountant,10,[],['Certified Public Accountant'],Accountant,100,Financial Accountant,95,Accounting Manager,85,Finance Analyst,80,Financial Controller,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3885,web designer resume creative with 10+ years of...,"['HTML5', 'CSS3', 'JavaScript', 'jQuery', 'Ado...",Bachelor of Science in Web Design and Development,15,[],[],Web Designer,100,UI/UX Designer,90,Frontend Developer,80,Web Application Developer,70,Digital Experience Designer,60
3886,stephanie smith senior web developer innovativ...,"['HTML5', 'CSS3', 'JavaScript', 'PHP', 'SQL', ...",BS in Web Development,8,[],[],Web Developer,100,Front End Developer,90,Software Engineer,70,Full Stack Developer,60,Backend Developer,50
3887,first last freelance web developer new york ci...,"['JavaScript', 'HTML', 'Microsoft SQL Server',...",Master of Science in Management with Honors,10,['Developed new web applications using ASP.NET...,['Java Programming'],Web Developer,100,Software Engineer,90,Backend Developer,80,Frontend Developer,75,Full Stack Developer,70
3888,karen philips web designer info profile addres...,"['WordPress', 'Drupal', 'HTML', 'CSS', 'JavaSc...",Web Designer,3,[],[],Web Designer,100,Frontend Developer,80,UX Designer,70,UI Designer,60,Digital Product Designer,50
3889,robert smith junior web developer phone email:...,"['HTML', 'CSS3', 'JavaScript', 'PHP', 'Photosh...",Bachelor of Science in Marketing,5,[],[],Web Developer,90,Frontend Developer,85,Junior Developer,80,Email Developer,75,Web Designer,70

In [ ]:
import nltk   # remove the like loved, loving to love only so not repeat the same word using prefix or suffix

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [ ]:
df['resume_text'].apply(stem)

1       howard gerrard account work experi dyrpjcom bi...
2       olivia ogilvi account pacif ave lo angel ca 90...
3       brooklyn ny stephen@beamjob com linkedin steph...
4       mari anderson sometown; co mac @somedomain com...
5       anna@novoresumecom anna gunther senior account...
                              ...
3885    web design resum creativ with 10+ year of expe...
3886    stephani smith senior web develop innov taskdr...
3887    first last freelanc web develop new york citi ...
3888    karen philip web design info profil address en...
3889    robert smith junior web develop phone email: i...
Name: resume_text, Length: 3265, dtype: object

In [ ]:
import re
data = []
for text in df['resume_text']:
    clean_text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    data.append(clean_text)

df['resume_text'] = data

In [ ]:
df['resume_text'][88]

'marnie wuckert hauck plaza san francisco ca 1 experience senior advocate padbergglover new york ny present familiar with various lines of coverage software qa testing multitier enterprise web applications strong whitebox webservice integration and server backend active contributor to open source projects knowledge level care guidelines ie locus interqual in inpatientacute setting or outpatient substance abuse asam placement criteria excel smartsheets technically focused claims driving initiatives handling complex the role demands handson claim management problem solving formulating settlement strategies for clients negotiation skills rolfson llc providing leadership taking ownership is essential project manage them a successful conclusion prior insurance carrier independent adjuster broker familiarity property manuscript policies time element adjudication processes procedures some boiler machinery breakdown applicable laws legal codes involving communication both verbal written at executive adequate computer relevant microsoft office outlook webbased medicaid patient population education oregon state university bachelors psychology creates business development plans forecasting by preparing efforts on behalf customer assessing customer needs regular basis validating strategic sales model alignment maintaining accurate data all activity product renewals retention existing customers building rapport conducting specific analysis expiration following industry trends enhancements platforms advises assigned accounts multinationalglobal selling additional products services customers finding multiple areas within identifying prospects evaluating their position among competitors researching analyzing options'

In [ ]:
df

,resume_text,skills,education,experience_years,projects,certifications,job_role_1,confidence_1,job_role_2,confidence_2,job_role_3,confidence_3,job_role_4,confidence_4,job_role_5,confidence_5
1,howard gerrard accountant work experience dyrp...,"['Accounting', 'Financial Accounting', 'VAT Re...",Bachelor of Commerce,12,[],[],Accountant,100,Financial Accountant,95,Budget Analyst,85,Cash Manager,80,Financial Controller,70
2,olivia ogilvy accountant pacific ave los angel...,"['Financial Reporting', 'Accounting', 'Reconci...",MBA,7,[],['Chartered Financial Analyst (CFA)'],Accountant,100,Financial Analyst,90,Accounting Manager,80,Finance Manager,70,Financial Controller,60
3,brooklyn ny stephenbeamjobs com linkedin steph...,"['QuickBooks', 'Taxjar', 'GAAP accounting prin...",MBA Accounting,9,[],['Certified Public Accountant (CPA)'],Accountant,100,Financial Controller,90,Accounting Manager,80,Finance Manager,70,Senior Accountant,100
4,marie anderson sometown co mac somedomain com ...,"['QuickBooks', 'SQL', 'SAP', 'Oracle', 'GAAP',...",Bachelor of Science in Accounting,10,[{'name': 'Tech Startup Accounting System Impl...,[],Accountant,100,Financial Analyst,90,Audit Specialist,85,Tax Accountant,80,Compliance Officer,75
5,annanovoresumecom anna gunther senior accounta...,"['Accounting', 'Financial Reporting', 'Cost Co...",Senior Accountant,10,[],['Certified Public Accountant'],Accountant,100,Financial Accountant,95,Accounting Manager,85,Finance Analyst,80,Financial Controller,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3885,web designer resume creative with 10 years of ...,"['HTML5', 'CSS3', 'JavaScript', 'jQuery', 'Ado...",Bachelor of Science in Web Design and Development,15,[],[],Web Designer,100,UI/UX Designer,90,Frontend Developer,80,Web Application Developer,70,Digital Experience Designer,60
3886,stephanie smith senior web developer innovativ...,"['HTML5', 'CSS3', 'JavaScript', 'PHP', 'SQL', ...",BS in Web Development,8,[],[],Web Developer,100,Front End Developer,90,Software Engineer,70,Full Stack Developer,60,Backend Developer,50
3887,first last freelance web developer new york ci...,"['JavaScript', 'HTML', 'Microsoft SQL Server',...",Master of Science in Management with Honors,10,['Developed new web applications using ASP.NET...,['Java Programming'],Web Developer,100,Software Engineer,90,Backend Developer,80,Frontend Developer,75,Full Stack Developer,70
3888,karen philips web designer info profile addres...,"['WordPress', 'Drupal', 'HTML', 'CSS', 'JavaSc...",Web Designer,3,[],[],Web Designer,100,Frontend Developer,80,UX Designer,70,UI Designer,60,Digital Product Designer,50
3889,robert smith junior web developer phone email ...,"['HTML', 'CSS3', 'JavaScript', 'PHP', 'Photosh...",Bachelor of Science in Marketing,5,[],[],Web Developer,90,Frontend Developer,85,Junior Developer,80,Email Developer,75,Web Designer,70

In [ ]:
df[['job_role_1', 'job_role_2', 'job_role_3', 'job_role_4', 'job_role_5']]

,job_role_1,job_role_2,job_role_3,job_role_4,job_role_5
1,Accountant,Financial Accountant,Budget Analyst,Cash Manager,Financial Controller
2,Accountant,Financial Analyst,Accounting Manager,Finance Manager,Financial Controller
3,Accountant,Financial Controller,Accounting Manager,Finance Manager,Senior Accountant
4,Accountant,Financial Analyst,Audit Specialist,Tax Accountant,Compliance Officer
5,Accountant,Financial Accountant,Accounting Manager,Finance Analyst,Financial Controller
...,...,...,...,...,...
3885,Web Designer,UI/UX Designer,Frontend Developer,Web Application Developer,Digital Experience Designer
3886,Web Developer,Front End Developer,Software Engineer,Full Stack Developer,Backend Developer
3887,Web Developer,Software Engineer,Backend Developer,Frontend Developer,Full Stack Developer
3888,Web Designer,Frontend Developer,UX Designer,UI Designer,Digital Product Designer
3889,Web Developer,Frontend Developer,Junior Developer,Email Developer,Web Designer

In [ ]:
lis = []
for cat in df['job_role_1']:
    str1 = cat.replace("-", "").replace(" ", "").lower()
    lis.append(str1)

df['job_role_1'] = lis

In [ ]:
lis = []
for cat in df['job_role_2']:
    str1 = cat.replace("-", "").replace(" ", "").lower()
    lis.append(str1)

df['job_role_2'] = lis

In [ ]:
lis = []
for cat in df['job_role_3']:
    str1 = cat.replace("-", "").replace(" ", "").lower()
    lis.append(str1)

df['job_role_3'] = lis

In [ ]:
lis = []
for cat in df['job_role_4']:
    str1 = cat.replace("-", "").replace(" ", "").lower()
    lis.append(str1)

df['job_role_4'] = lis

In [ ]:
lis = []
for cat in df['job_role_5']:
    str1 = cat.replace("-", "").replace(" ", "").lower()
    lis.append(str1)

df['job_role_5'] = lis

In [ ]:
df.shape

(2707, 16)

In [ ]:
df

,resume_text,skills,education,experience_years,projects,certifications,job_role_1,confidence_1,job_role_2,confidence_2,job_role_3,confidence_3,job_role_4,confidence_4,job_role_5,confidence_5
1,howard gerrard accountant work experience dyrp...,"['Accounting', 'Financial Accounting', 'VAT Re...",Bachelor of Commerce,12,[],[],accountant,100,financialaccountant,95,budgetanalyst,85,cashmanager,80,financialcontroller,70
2,olivia ogilvy accountant pacific ave los angel...,"['Financial Reporting', 'Accounting', 'Reconci...",MBA,7,[],['Chartered Financial Analyst (CFA)'],accountant,100,financialanalyst,90,accountingmanager,80,financemanager,70,financialcontroller,60
3,brooklyn ny stephenbeamjobs com linkedin steph...,"['QuickBooks', 'Taxjar', 'GAAP accounting prin...",MBA Accounting,9,[],['Certified Public Accountant (CPA)'],accountant,100,financialcontroller,90,accountingmanager,80,financemanager,70,senioraccountant,100
4,marie anderson sometown co mac somedomain com ...,"['QuickBooks', 'SQL', 'SAP', 'Oracle', 'GAAP',...",Bachelor of Science in Accounting,10,[{'name': 'Tech Startup Accounting System Impl...,[],accountant,100,financialanalyst,90,auditspecialist,85,taxaccountant,80,complianceofficer,75
5,annanovoresumecom anna gunther senior accounta...,"['Accounting', 'Financial Reporting', 'Cost Co...",Senior Accountant,10,[],['Certified Public Accountant'],accountant,100,financialaccountant,95,accountingmanager,85,financeanalyst,80,financialcontroller,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3885,web designer resume creative with 10 years of ...,"['HTML5', 'CSS3', 'JavaScript', 'jQuery', 'Ado...",Bachelor of Science in Web Design and Development,15,[],[],webdesigner,100,ui/uxdesigner,90,frontenddeveloper,80,webapplicationdeveloper,70,digitalexperiencedesigner,60
3886,stephanie smith senior web developer innovativ...,"['HTML5', 'CSS3', 'JavaScript', 'PHP', 'SQL', ...",BS in Web Development,8,[],[],webdeveloper,100,frontenddeveloper,90,softwareengineer,70,fullstackdeveloper,60,backenddeveloper,50
3887,first last freelance web developer new york ci...,"['JavaScript', 'HTML', 'Microsoft SQL Server',...",Master of Science in Management with Honors,10,['Developed new web applications using ASP.NET...,['Java Programming'],webdeveloper,100,softwareengineer,90,backenddeveloper,80,frontenddeveloper,75,fullstackdeveloper,70
3888,karen philips web designer info profile addres...,"['WordPress', 'Drupal', 'HTML', 'CSS', 'JavaSc...",Web Designer,3,[],[],webdesigner,100,frontenddeveloper,80,uxdesigner,70,uidesigner,60,digitalproductdesigner,50
3889,robert smith junior web developer phone email ...,"['HTML', 'CSS3', 'JavaScript', 'PHP', 'Photosh...",Bachelor of Science in Marketing,5,[],[],webdeveloper,90,frontenddeveloper,85,juniordeveloper,80,emaildeveloper,75,webdesigner,70

In [ ]:
df.shape

(2707, 16)

In [ ]:
df.to_csv('ready_for_training_resume.csv')

In [ ]:
df['resume_text'][98]

'gianna daniels main street neu cityland ca cell exampleemail a example com summary motivated crop applicator experienced in peak and offfpeak operations safely handle all chemicals proliciently complete tasks flexible schedule clean driving record with ability t0 travel highlights good communication abilities hazmat chemical knowledge regulatory compliance safetvconscious always on time can life 75 pounds highly accurate basic math skills efficient reliable experience wilton growers january current new citvland handle blend deliver seeds correct farm locations mix prepare fertilizers for application apply fertilizer agricultural crops run various machinery including sprayer row liquid machines daily vehicle inspections cleaning manage supply inventory track usages request stock roswald association may 20os december id arrived at job sites o ready to work performed preinspection ol equipment supplies before beginning cach updated logs completed paperwork accurately timely manner properly applied products plant protection fertilization inspected repairs as needed assisted warehouse duties maimtain followed company standards safe handling practices government regulations times pershing farms august april trainee canton sd operated sprayers floalers other heavy equipment spread sprayed maintained rolling ensured stayed use preventative maintenance techniques certifications licenses cdl license endorsement qualified applicator certification'

In [ ]:
counts = df["job_role_1"].value_counts()

valid_classes = counts[counts >= 2].index

df = df[df["job_role_1"].isin(valid_classes)]

In [ ]:
X = df['resume_text']
y = df['job_role_1']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2165,), (542,), (2165,), (542,))

In [ ]:
vectorizer = TfidfVectorizer(
    stop_words="english",
    lowercase=True,
    max_features=50000,
    ngram_range=(1, 3),
    min_df=2,
    max_df=0.90
)

print(vectorizer)

TfidfVectorizer(max_df=0.9, max_features=50000, min_df=2, ngram_range=(1, 3),
                stop_words='english')

In [ ]:
print(type(X_train))

<class 'pandas.core.series.Series'>

In [ ]:
print(X_train.head())

1157    shaun parvelu operations manager phone linkedl...
3872    parker everhart yourenuile sial com jukcdtn co...
2533    jessica claire montgomery st ioth floor resume...
537     michele lakin roosevelt mountains los angeles ...
1777    jessica claire montgomery street san francisco...
Name: resume_text, dtype: object

In [ ]:
len(X_train)

2165

In [ ]:
X_train_new = vectorizer.fit_transform(X_train)
X_test_new = vectorizer.transform(X_test)

In [ ]:
# from sklearn.preprocessing import OrdinalEncoder

# encoder = OrdinalEncoder(
#     handle_unknown="use_encoded_value",
#     unknown_value=-1
# )

# # Fit on training data
# y_train_new = encoder.fit_transform(y_train)

# # Transform test data
# y_test_new = encoder.transform(y_test)

In [ ]:


# y_train_new = pd.DataFrame(
#     y_train_new,
#     columns=y_train.columns,
#     index=y_train.index
# )

# y_test_new = pd.DataFrame(
#     y_test_new,
#     columns=y_test.columns,
#     index=y_test.index
# )

In [ ]:
le = LabelEncoder()
y_train_new = le.fit_transform(y_train)
y_test_new = le.transform(y_test)

In [ ]:
# model = LogisticRegression()

# model.fit(X_train_new, y_train_new)

In [ ]:
# from sklearn.svm import LinearSVC

# model = LinearSVC(random_state=42)
# model.fit(X_train_new, y_train_new)

In [ ]:
from sklearn.calibration import CalibratedClassifierCV
from sklearn.svm import LinearSVC

base_model = LinearSVC(random_state=42)

model = CalibratedClassifierCV(base_model)

model.fit(X_train_new, y_train_new)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

CalibratedClassifierCV(estimator=LinearSVC(random_state=42))

In [ ]:
y_pred = model.predict(X_test_new)

accuracy_score(y_test_new, y_pred)

0.6033210332103321

In [ ]:
y_pred_labels = model.inverse_transform(y_pred)

AttributeError: 'CalibratedClassifierCV' object has no attribute 'inverse_transform'

In [ ]:
resume = """
Python developer with 3 years of experience in Django,
Flask, REST API, MySQL, Machine Learning and Docker.
"""

In [ ]:
resume_vector = vectorizer.transform([resume])

In [ ]:
prediction = model.predict(resume_vector)

In [ ]:
job_role = le.inverse_transform(prediction)

print(job_role[0])

In [ ]:
import numpy as np

probabilities = model.predict_proba(resume_vector)[0]

top5 = np.argsort(probabilities)[::-1][:5]

for i, idx in enumerate(top5, start=1):

    role = le.inverse_transform([idx])[0]
    confidence = probabilities[idx] * 100

    print(f"{i}. {role} ({confidence:.2f}%)")

In [ ]:
print(df["job_role_1"].nunique())

In [ ]:
print(df["job_role_1"].value_counts().head(20))

In [ ]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_new)

print("Accuracy:", accuracy_score(y_test_new, y_pred))

In [ ]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("X_train_new:", X_train_new.shape)
print("X_test_new :", X_test_new.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

print("y_pred:", y_pred.shape)

In [ ]:
print(y_train_new.shape)
print(y_test_new.shape)