In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("Resume.csv")
df.shape

(2484, 4)

In [3]:
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [4]:
df.sample(4)

,ID,Resume_str,Resume_html,Category
2225,60489316,"MANAGER, ADVISORY, PERFORMANCE IMPROV...","<div class=""fontsize fontface vmargins hmargin...",BANKING
2089,18133495,"P DIRECTOR, INFORMATION SYSTEMS P...","<div class=""fontsize fontface vmargins hmargin...",PUBLIC-RELATIONS
820,17660419,GUEST LECTURER Accompli...,"<div class=""fontsize fontface vmargins hmargin...",FITNESS
429,21550454,KINDERGARTEN TEACHER Summar...,"<div class=""fontsize fontface vmargins hmargin...",TEACHER

In [5]:
df['Resume_str'][0]

"         HR ADMINISTRATOR/MARKETING ASSOCIATE\n\nHR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate\n\nHR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate \xa0   Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.    "

In [6]:
df = df.iloc[:,[1,3]]

In [7]:
df.shape

(2484, 2)

In [8]:
df['Resume_str'][1]

"         HR SPECIALIST, US HR OPERATIONS       Summary     Versatile  media professional with background in Communications, Marketing, Human Resources and Technology.\xa0        Experience     09/2015   to   Current     HR Specialist, US HR Operations    Company Name   －   City  ,   State       Managed communication regarding launch of Operations group, policy changes and system outages      Designed standard work and job aids to create comprehensive training program for new employees and contractors         Audited job postings for old, pending, on-hold and draft positions.           Audited union hourly, non-union hourly and salary background checks and drug screens             Conducted monthly new hire benefits briefing to new employees across all business units               Served as a link between HR Managers and vendors by handling questions and resolving system-related issues         Provide real-time process improvement feedback on key metrics and initiatives  Successfully re-branded US HR Operations SharePoint site  Business Unit project manager for RFI/RFP on Background Check and Drug Screen vendor         01/2014   to   05/2015     IT, Marketing and Communications Co-op    Company Name   －   City  ,   State      Posted new articles, changes and updates to corporate SharePoint site including graphics and visual communications.  Researched and drafted articles and feature stories to promote company activities and programs.  Co-edited and developed content for quarterly published newsletter.  Provided communication support for internal and external events.  Collaborated with Communication team, media professionals and vendors to determine program needs for print materials, web design and digital communications.  Entrusted to lead product, service and software launches for Digital Asset Management tool, Marketing Toolkit website and Executive Tradeshows Calendar.  Created presentations for management and executive approval to ensure alignment with corporate guidelines and branding.  Maintained the MySikorsky SharePoint site and provided timely solutions to mitigate issues.\xa0\xa0\xa0\xa0  Created story board and produced video for annual IT All Hands meeting.         10/2012   to   01/2014     Relationship Coordinator/Marketing Specialist    Company Name   －   City  ,   State       Partnered with vendor to manage the in-house advertising program consisting of print and media collateral pieces.     Coordinated pre-show and post-show activities at trade shows.     Managed marketing campaigns to generate new business and to support partner and sales teams.     Ordered marketing collateral for meetings, trade shows and advisors.    Improved, administered and modified marketing programs to increase product awareness.  Assisted in preparing internal promotional publications, managed marketing material inventory and supervised distribution of publications to ensure high quality product output.  Coordinated marketing materials including brochures, promotional materials and products.  Partnered with graphic designers to develop appropriate materials and branding for brochures.  Used tracking and reporting systems for sales leads and appointments.         09/2009   to   10/2012     Assistant Head Teller    Company Name   －   City  ,   State       Received an internal audit score of  100 %.     Performed daily and monthly audits of ATM machines and tellers.     Educated customers on a variety of retail products and available credit options.       Consistently met or exceeded quarterly sales goals     Promoted products and services to\ncustomers while maintaining company brand identity\n\n·\xa0\xa0\xa0\xa0\n  Implemented programs to achieve\nand exceed customer and company participation goals\xa0\n\n\xa0  Organized company sponsored events on campus resulting in increased\nbrand awareness\n\n·\xa0\xa0\xa0\xa0\n  Coached peers on\nthe proper use of programs to improve work flow efficiency  Utilized product knowledge to successfully sell\nto and refer clients based on individual needs  Promoted marketing the grand opening\nof new branch locations to strengthen company brand affinity\n\n·\xa0\xa0\xa0\xa0   Organized company sponsored events\nresulting in increased brand awareness and improved sales\n\n·\xa0\xa0\xa0\xa0   Coached peers on the proper use of\nprograms to increase work flow efficiency\n\n          Senior Producer - 2014 SHU Media Exchange    Company Name   －   City  ,   State      Planned and executed event\xa0focusing on Connecticut's creative corridor, growth of industry and opportunities that come with development. A\xa0 panel of industry professionals addressed topics related to media and hosted a question and answer session for approximately 110 attendees. Following the forum, guests were invited to engage in networking and conversation at a post-event reception.         Education     2014     Master of Arts  :   Corporate Communication & Public Relations    Sacred Heart University   －   City  ,   State             2013     Bachelor of Arts  :   Relational Communication    Western Connecticut State University   －   City  ,   State              Skills    Adobe Photoshop, ADP, Asset Management, branding, brochures, content, Customer Care, Final Cut Pro, graphics, graphic, HR, Illustrator, InDesign, Innovation, inventory, Lotus Notes, marketing, marketing materials, marketing material, materials, Microsoft Office, SharePoint, newsletter, presentations, process improvement, Project Management, promotional materials, publications, Quality, real-time, Recruitment, reporting, RFP, sales, stories, Employee Development, video, web design, website, articles   "

In [9]:
df.sample(4)

                                             Resume_str      Category
2008           OWNER/PROJECT MANAGER       Executive...  CONSTRUCTION
535            FACULTY, CLINICAL INSTRUCTOR, & CLINI...      ADVOCATE
784            OWNER       Summary     Results-orien...    HEALTHCARE
2466           MANAGEMENT AND PROGRAM ANALYSIS      ...      AVIATION

In [10]:
df['Resume_str'][165]

'         PRODUCTION DESIGNER       Summary     Specializing in Art Department I have had many different opportunities, as well as many different positions. I love working with a team and collaborating, though I can work alone and am happy to do what is asked. I am not concerned with receiving a position of power, I listen to instructions very intently. However if the situation called for it I can easily give instruction in a polite and respectful manner. I am also very skilled with almost all power tools, safety laws, and am a skilled teacher if the occasion calls for it. Though I enjoy the work in art department I am capable of filling any position if need be. I am very passionate about Film and the entertainment industry and will always be willing to help in any way I can.       Highlights          Work well with others and under pressure. Quick learner and yearns to excel. Keeps busy and takes  initiative with things within my department. I am a great delegator when it comes to leading a team,  however I am also very good at following instructions and the chain of command. Sketching and hand  drafting. Proficient in MS Word & Powerpoint. Experienced in Photoshop, Aftereffects, Avid Media, and  Google Sketchup.              Accomplishments     I have only been working in the industry for 3 years yet I already have 6 going on 7 projects listed on IMDB.   I edited a screenplay, turned 50 pages of Dialogue into 127 pages of a well plotted Romance Comedy and full length feature.   I have brought many people together and helped to create work opportunities for the people I believe in and that I know will do the job well.       Experience      Production Designer          Jul 2014   to   Aug 2014      Company Name   －   City  ,   State     Referred outside hire on a short, 15 minute student film with The New York Film Academy.  A drama about a man, his life, and the life he gave and provided for his three children, one of which is a young deaf boy who was living on the streets until the main character takes him in; in turn leading to family turmoil within his little family.  Coordinated the art department needs based on scheduling, handled art department budget and set coordinator during the build.         Director of Photography               Sep 2013   to   Sep 2013      Company Name   －   City  ,   State     A one-day photo shoot for a Non Profit organization called The Bird Room.  Found locations with natural lighting in Downtown Los Angeles for headshots, and artistic images for website, with dancers, actors, and our lovely group of donators.         Set Decorator and Props assist "Small Heist"     Mar 2013   to   Mar 2013      Company Name   －   City  ,   State    A teaser trailer and promotional short film involving 5 Women who steal millions worth in diamonds but get played for fools.   Dressed the set, helped with continuity, costuming, prop assist. , and also took over as art director when my production designer was called away.        Art Director     Apr 2013   to   Jun 2013      Company Name   －   City  ,   State     My Name is Vivienne An independent feature film, that took nearly 3 weeks to shoot; about a superficial actress trying to become famous, and with no talent, and how she comes to terms with the reality of working to achieve a goal.  I also acted as prop master and set dresser, as it was a low budget film, also I played the part of production designer when my boss was unable to make it.         Production Designer          Distinguished Gentlemen     Nov 2012   to   Jan 2013      Company Name   －   City  ,   State     An Independent sitcom, a three-day shoot, with 7 child actors between the ages of 9 and 13.  Located.  and purchased all the props and acted as prop master as well.         Set decorator     Jan 2013   to   Feb 2013      Company Name   －   City  ,   State    A short film that follows the strange love story of a man with a very unusual sexual relationship with his plants, and learning to accept himself, finding there is some one out there for every one.   Dressed the locations, props assist., created graphics, and was made Art director anytime the production designer was called away or setting up the next location, did art department runs an returns        Art Department                              "Science of Love"     Jan 2014   to   Jan 2014      Company Name   －   City  ,   State    Two day music video shoot - Three day long Job   Helped to finish building and painting the set, also involved in tear down. Dressed sets, did resets, and props assist.        Set decorator/ Props Assist          The Coed and the Zombie Stoner     Dec 2013   to   Dec 2013      Company Name   －   City  ,   State    Dressed locations, tore down dress, props Assist. prepped locations day before crew was to arrive.        Art Director/ Art Department Coordinator/ Fire and Safety Management     Jun 2014   to   Jul 2014      Company Name   －   City  ,   State    3 week long feature Film shoot.  A serial killer sequel that took place in an abbandoned annual huanted house.  I made sure the location was safe and fire hazard free upon crew arrival. Dressed locations, built props, Props master, Rigged location for easier grip managing that also acted as support for already established walls.        Camera Assist. / Front door attendant / Audience member     Jan 2014   to   Jan 2014      Company Name   －   City  ,   State    The first ever Stand up Comedy Show at the Ivar theatre.   Helped prep Cameras before guest arrival. Tended to talent. Checked I.D.s at the front door. Acted as a seat filler/audience member and was actually brought in by one comedian to finish his joke.        Set designer and coordinator     Aug 2013   to   Sep 2013      Company Name   －   City  ,   State    I coordinated the build of two sets on one sound stage. One set was an easy break set that was made to mimic Goerge Millies A trip to the Moon Crash landing. The other was made to mimic a scene From one of Mae wests films.         Miscellaneous Crew               Dude Bro Party Massacre 3     Apr 2014   to   Apr 2014      Company Name   －   City  ,   State    Production Assistant, stood at the front gate asking for proper indentification and directed arriving cast members to their proper waiting areas, as well as to costuming and make up. Brought water bottles to crew and made sure everything was locked down tight.        Education      Associate of Science  ,   Film Production   September 2013     The Los Angeles Film School   －   City  ,   State  ,   USA    Taught the basics of every aspect and department in the film making experience. Was awarded with an   Associates in the Science of Film.        High School Diploma     2010     Eagle Rock jr./Sr. High school   －   City  ,   State  ,   USA    Graduated with a 3.0 and majored in CSI (Advanced biology) and Horticulture.        Skills     Aftereffects, Photo, Photoshop, AD, Art, Avid, budget, drafting, edit, Film, lighting, director, excel, Powerpoint, MS Word, natural, composer, next, Camera, Profit, Quick learner, reality, safety, scheduling, Sketching, website    '

In [11]:
df['Resume_str'][600]

"         DIRECTOR OF BUSINESS DEVELOPMENT         Summary     Dedicated and driven sales and marketing strategist with 8+ years' experience in cloud software industry.  Proven ability to research, develop, and implement technical sales and marketing plans.  Expert in the technical content development of sales collateral that effectively reinforces the solution benefits.  Skilled writer, trainer and presenter.  Fast learner, works well under pressure, committed to team success.       Highlights          DIRECTOR OF BUSINESS DEVELOPMENT, PRIVACY DATA SYSTEMS, LLC  Dedicated and driven sales and marketing strategist with 8+ years' experience in cloud software industry.  Proven ability to research, develop, and implement technical sales and marketing plans.  Expert in the technical content development of sales collateral that effectively reinforces the solution benefits.  Skilled writer, trainer and presenter.  Fast learner, works well under pressure, committed to team success.  skills & core competencies   Presales and Implementation Support  Development of Marketing Strategies  Competitive Analysis, Market Research  Development of Training Materials  Product Positioning & Branding  Product Demonstrations  Development of Sales Collateral  Public & Media Relations  Web & Print Content Development  Client Support (Post sales)  Ability to listen, understand, and relay business needs to technical and development teams  Adobe Creative Suite: Photoshop, Illustrator, InDesign, Adobe Acrobat  CRM: Proficiency in administration of Salesforce and Microsoft Dynamics CRM applications including but not limited to customization, reports and dashboards, and data import/export  Planning/Organization  Exemplary planning and organizational skills, with high degree of detail orientation  Innovative problem-solver who can generate solutions using creativity and past experience  Resourceful and efficient project manager  Skilled at wearing many hats and thinking outside of the box                Experience      Company Name    Director of Business Development   07/2007   to   09/2015       Previous - Director Sales & Marketing Privacy Data Systems, LLC is a software development company that provides SenditCertified , a patented cloud-based secure communications platform.  SenditCertified  provides encrypted messaging and large file transfer, eSignatures, cloud-based encrypted storage, and biometric authentication - and is delivered via web, desktop and mobile apps, MS Outlook integration, and customized API/web services.  Contribute to the development and refinement of the company's vision and strategy Support the overall process of company management and growth of new business channels Liaise with other department heads on the implementation of the company's strategic and operational plans Develop, review, and report on the business development's strategy, ensuring the strategic objectives are well understood and executed by the team Ensure efficient and effective marketing and advertising planning Perform market analyses, research competitive landscape Develop and manage strategic sales opportunities Management of VAR/MSP sales channels Management of inside and outside sales resources Design and administer the company's CRM system (Salesforce) including reporting, dashboards, custom applications and data management.          Director of Franchise Sales   01/2003   to   12/2007       Corporate Atlantic Region, Help-U-Sell Real Estate Assisted Regional Director in management of large 9-state region Oversaw and executed marketing to potential franchisee candidates Managed consultative sales process from initial inquiry to close Utilized technology to increase efficiency during sales process.          Company Name       09/1996   to   05/1999       Analyzed product need on both company-wide and individual-store basis Allocated merchandise units based on intricate sales criteria Inspected incoming merchandise for quality control Worked in collaboration with the purchasing team professional skills Communications Exceptional listener and communicator Effectively conveys information both verbally and in writing Highly analytical thinking with talent for streamlining complex work processes Talent for locating and analyzing online information and market data.          Education      Bachelor of Science     May 1996     Texas A&M University                  Interests    2007-Present\nYouth Rec. Cheerleading Coach - Allen Sports Association\n2010-Present\nLeague Director - Allen Sports Association Board      Additional Information      community involvement 2007-Present Youth Rec. Cheerleading Coach - Allen Sports Association 2010-Present League Director - Allen Sports Association Board         Skills    Adobe Creative Suite, Adobe Acrobat, Photoshop, advertising, API, benefits, Branding, business development, competitive, Competitive Analysis, Content Development, creativity, CRM, Client Support, data management, Illustrator, InDesign, DIRECTOR, marketing plans, Market Research, Marketing Strategies, marketing strategist, marketing, market, Media Relations, messaging, Microsoft Dynamics, MS Outlook, works, communicator, organizational skills, outside sales, Positioning, presenter, problem-solver, processes, purchasing, quality control, Fast learner, Real Estate, reporting, research, Sales, software development, strategy, strategic, technical sales, trainer, Training Materials, vision, writer   "

In [12]:
df['Resume_str'].duplicated().sum()

np.int64(2)

In [13]:
df = df.drop_duplicates(subset='Resume_str', keep = 'first')

In [14]:
df['Resume_str'].duplicated().sum()

np.int64(0)

In [15]:
df['Resume_str'].isnull().mean() * 100

np.float64(0.0)

In [16]:
# df['Resume_str'][0].replace(",", "").lower().split()

In [17]:
st = df['Resume_str'].index
st

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482],
      dtype='int64', length=2482)

In [18]:
import re
cleaned_resumes = []

for resume in df['Resume_str']:
    lis = resume.replace(",", "").replace("/", "").replace('.', '').replace('(', '').replace('-', '').replace(')', '').replace('_', '').lower().split()
    lis = [word for word in lis if not word.isdigit()]
    obj = list(dict.fromkeys(lis))
    jo = " ".join(obj)
    cleaned_resumes.append(jo)

df['Resume_str'] = cleaned_resumes

In [19]:
df

                                             Resume_str  Category
0     hr administratormarketing associate administra...        HR
1     hr specialist us operations summary versatile ...        HR
2     hr director summary over years experience in r...        HR
3     hr specialist summary dedicated driven and dyn...        HR
4     hr manager skill highlights skills department ...        HR
...                                                 ...       ...
2478  advanced level wheeled vehicle mechanic career...  AVIATION
2479  rank: sgte5 non commissioned officer in charge...  AVIATION
2480  government relations communications and organi...  AVIATION
2481  geek squad agent professional profile it suppo...  AVIATION
2482  program director office manager summary highly...  AVIATION

[2482 rows x 2 columns]

In [20]:
df['Resume_str'][0]

"hr administratormarketing associate administrator summary dedicated customer service manager with 15+ years of experience in hospitality and management respected builder leader customerfocused teams; strives to instill a shared enthusiastic commitment highlights focused on satisfaction team marketing savvy conflict resolution techniques training development skilled multitasker client relations specialist accomplishments missouri dot supervisor certification certified by ihg loyalty segment hilton worldwide general accomplished trainer for cross server systems such as onq micros opera pms fidelio reservation system ors holidex completed courses seminars sales strategies inventory control loss prevention safety time leadership performance assessment dec current company name － city state helps develop policies directs coordinates activities employment compensation labor benefits employee services prepares separation notices related documentation keeps records plans participation insurance pension plan personnel transactions hires promotions transfers reviews terminations statistics government reporting advises appropriate issues administers programs life health dental vacation sick leave absence assistance designed created collateral meetings trade shows executives managed the inhouse advertising program consisting print media pieces assisted complete design launch company's website months an official page facebook facilitate interaction customers analyzed ratings programming features competitors evaluate effectiveness advanced medical claims analyst mar reviewed bills accuracy treatments tests hospital stays prior sanctioning trained interpret codes icd9 cpt terminology commonly used billing fully understand paperwork that is submitted healthcare providers required have organizational analytical skills well computer knowledge procedures standards data analysis laws regarding assistant jun performed duties including but not limited budgeting financial accounting human resources payroll purchasing established maintained close working relationships all departments hotel ensure maximum operation productivity morale guest handled daily operations reported directly corporate office hired staff overall objectives goals emphasis high public local businesses chamber commerce executive support jul provided various department heads frontend friendly efficient ensured swift preserve while complying exemplified secondtonone delivery interactions potential clients & front owner partner may price integrity coordinator aug education na business administration jefferson college school diploma prep studies sainte genevieve senior awarded american shrubel scholarship ads layout posters presentations"

In [21]:
import nltk   # remove the like loved, loving to love only so not repeat the same word using prefix or suffix

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [22]:
df['Resume_str'].apply(stem)

0       hr administratormarket associ administr summar...
1       hr specialist us oper summari versatil media p...
2       hr director summari over year experi in recrui...
3       hr specialist summari dedic driven and dynam w...
4       hr manag skill highlight skill depart startup ...
                              ...
2478    advanc level wheel vehicl mechan career focu t...
2479    rank: sgte5 non commiss offic in charg brigad ...
2480    govern relat commun and organiz develop direct...
2481    geek squad agent profession profil it support ...
2482    program director offic manag summari highli pe...
Name: Resume_str, Length: 2482, dtype: object

In [23]:
df

                                             Resume_str  Category
0     hr administratormarketing associate administra...        HR
1     hr specialist us operations summary versatile ...        HR
2     hr director summary over years experience in r...        HR
3     hr specialist summary dedicated driven and dyn...        HR
4     hr manager skill highlights skills department ...        HR
...                                                 ...       ...
2478  advanced level wheeled vehicle mechanic career...  AVIATION
2479  rank: sgte5 non commissioned officer in charge...  AVIATION
2480  government relations communications and organi...  AVIATION
2481  geek squad agent professional profile it suppo...  AVIATION
2482  program director office manager summary highly...  AVIATION

[2482 rows x 2 columns]

In [24]:
df['Resume_str'][0]

"hr administratormarketing associate administrator summary dedicated customer service manager with 15+ years of experience in hospitality and management respected builder leader customerfocused teams; strives to instill a shared enthusiastic commitment highlights focused on satisfaction team marketing savvy conflict resolution techniques training development skilled multitasker client relations specialist accomplishments missouri dot supervisor certification certified by ihg loyalty segment hilton worldwide general accomplished trainer for cross server systems such as onq micros opera pms fidelio reservation system ors holidex completed courses seminars sales strategies inventory control loss prevention safety time leadership performance assessment dec current company name － city state helps develop policies directs coordinates activities employment compensation labor benefits employee services prepares separation notices related documentation keeps records plans participation insurance pension plan personnel transactions hires promotions transfers reviews terminations statistics government reporting advises appropriate issues administers programs life health dental vacation sick leave absence assistance designed created collateral meetings trade shows executives managed the inhouse advertising program consisting print media pieces assisted complete design launch company's website months an official page facebook facilitate interaction customers analyzed ratings programming features competitors evaluate effectiveness advanced medical claims analyst mar reviewed bills accuracy treatments tests hospital stays prior sanctioning trained interpret codes icd9 cpt terminology commonly used billing fully understand paperwork that is submitted healthcare providers required have organizational analytical skills well computer knowledge procedures standards data analysis laws regarding assistant jun performed duties including but not limited budgeting financial accounting human resources payroll purchasing established maintained close working relationships all departments hotel ensure maximum operation productivity morale guest handled daily operations reported directly corporate office hired staff overall objectives goals emphasis high public local businesses chamber commerce executive support jul provided various department heads frontend friendly efficient ensured swift preserve while complying exemplified secondtonone delivery interactions potential clients & front owner partner may price integrity coordinator aug education na business administration jefferson college school diploma prep studies sainte genevieve senior awarded american shrubel scholarship ads layout posters presentations"

In [25]:
import re
data = []
for text in df['Resume_str']:
    clean_text = re.sub(r'[^a-zA-Z\s]', '', text)
    data.append(clean_text)

df['Resume_str'] = data

In [26]:
df['Resume_str'][44]

'hr coordinator summary highly accomplish human resource professional proficient at developing policy standard operating procedures and best practices proven expertise in recruiting training employee development retention performance management conflict resolution adept managing multiple projects simultaneously while demonstrating high standards with astute attention to details deadlines organizing large amounts of time sensitive information evaluating priorities able thrive under pressure maintaining enthusiasm motivation ms word kronos excel powerpoint outlook hcms experience apr current company name  city state ensured compliance federal local laws aramark job postings were posted onsite utilizing an active board all open positions are the appropriate agencies assists district safety leader key processes including administration workers compensation component manager monitor processed new hire paperwork ensures completion background checks truescreen is wage  hour oversight include applicant tally offers made conduct legally sound investigations mediate disputesissues between managers employees bring organizational structure wages position classificationjob descriptions aligned business necessity order meet strategic initiatives use effective efficient talent selection managerial coachingcounseling related procedure affirmative action planning actively executes staffing strategy unit level needs train areas such as interviewing hiring terminations promotions sexual harassment ensuring a positive progressive work environment proper disciplinary implementation engagement strategies updated manual covering codes fmla utilization improvement plans needed encore recognition program was implemented appreciation for our clients consumers administered two union contracts within partner companies established relationship staff members interact representatives handled grievance assistance solve labor disputes environments controlled placement schedules manage payroll functions biweekly submitting bonuses verified salaries managed ptovac accrual review handle unemployment claims owneroperator jan efficiently administrativefinancialaccounting purchasing inventory control product service supplier relations effectively interview schedule direct evaluate team strong focus on conveyance quality customer apply superior communication skills toward diplomatically addressing troubleshooting resolving issues started notforprofit animal rescue organization where i maintained shelter office but not limited assisting public intake adoptions redemptions licenses rental rate by surveying rates calculating overhead costs depreciation taxes profit goals attracted tenants advertising vacancies obtaining referrals from tenants explaining advantages location services showing units accomplished financial objectives collecting rents paying bills forecasting requirements preparing annual budget scheduling expenditures analyzing variances initiating corrective achieved solvency through cost reduction implementing systems achieve  rent delinquency maintain building contracting maintenance supervising repairs created welcoming supportive residents visitors property associates filed court documents eviction attends scheduled hearings landlords representative prepared reports summarizing data trends knowledge participating educational opportunities reading publications personal networks organizations accepting ownership accomplishing different requests exploring opportunities add value accomplishments interviewed contractors delivery education robert morris college us chicago il references available request certifications servsafe food protection certification department health certified manger resources pending affiliations member shrm receptionist retail sales budget accounting administrativefinancial buyingprocurement financialaccounting bi intelligence coaching pto excellent multitasker'

In [27]:
df['Category'].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
ACCOUNTANT                118
ENGINEERING               118
CHEF                      118
FINANCE                   117
FITNESS                   117
AVIATION                  116
SALES                     116
BANKING                   115
HEALTHCARE                115
CONSULTANT                115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [28]:
lis = []
for cat in df['Category']:
    str1 = cat.replace("-", "").replace(" ", "").lower()
    lis.append(str1)

df['Category'] = lis

In [29]:
df['Category'].value_counts()

Category
informationtechnology    120
businessdevelopment      120
advocate                 118
accountant               118
engineering              118
chef                     118
finance                  117
fitness                  117
aviation                 116
sales                    116
banking                  115
healthcare               115
consultant               115
construction             112
publicrelations          111
hr                       110
designer                 107
arts                     103
teacher                  102
apparel                   97
digitalmedia              96
agriculture               63
automobile                36
bpo                       22
Name: count, dtype: int64

In [30]:
df

                                             Resume_str  Category
0     hr administratormarketing associate administra...        hr
1     hr specialist us operations summary versatile ...        hr
2     hr director summary over years experience in r...        hr
3     hr specialist summary dedicated driven and dyn...        hr
4     hr manager skill highlights skills department ...        hr
...                                                 ...       ...
2478  advanced level wheeled vehicle mechanic career...  aviation
2479  rank sgte non commissioned officer in charge b...  aviation
2480  government relations communications and organi...  aviation
2481  geek squad agent professional profile it suppo...  aviation
2482  program director office manager summary highly...  aviation

[2482 rows x 2 columns]

In [50]:
X_train, X_test, y_train, y_test = train_test_split(df['Resume_str'], df['Category'], test_size=0.2, random_state=42, stratify=df['Category'])

X_train.shape, X_test.shape

((1985,), (497,))

In [51]:
X_train

2076    associate vice president for college advanceme...
1857    accountant summary flexible bookkeeper who ada...
1482    finance director summary with experience in st...
836     operations manager skills human resources year...
182     lead interaction designer summary senior uxui ...
                              ...
1464    administrative assistant career overview i wou...
1345    adjuster experience to current company name  c...
1305    digital marketing associate summary dynamic an...
1675    cfo assistantexecutive administratorhr manager...
2020    assistant project manager professional summary...
Name: Resume_str, Length: 1985, dtype: object

In [66]:
vectorizer = TfidfVectorizer(stop_words = 'english',ngram_range=(1,2),
    min_df=2,
    max_df=0.95)

In [67]:
X_train_new = vectorizer.fit_transform(X_train)
X_test_new = vectorizer.transform(X_test)

In [68]:
X_train_new.shape

(1985, 78204)

In [69]:
lb = LabelEncoder()
y_train_new = lb.fit_transform(y_train)
y_test_new = lb.transform(y_test)

In [70]:
y_train_new.shape

(1985,)

In [71]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_new, y_train_new)

y_pred = lr.predict(X_test_new)

accuracy_score(y_test_new, y_pred)

0.5653923541247485

In [72]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train_new, y_train_new)

y_pred = dtc.predict(X_test_new)

accuracy_score(y_test_new, y_pred)

0.5050301810865191

In [73]:
from sklearn.svm import LinearSVC

model = LinearSVC()

model.fit(X_train_new, y_train_new)

y_pred = model.predict(X_test_new)
accuracy_score(y_test_new, y_pred)

0.6217303822937625

In [74]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_new, y_train_new)

y_pred = model.predict(X_test_new)
accuracy_score(y_test_new, y_pred)

0.4949698189134809

In [75]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train_new, y_train_new)

y_pred = model.predict(X_test_new)
accuracy_score(y_test_new, y_pred)

0.6116700201207244

In [76]:
from sklearn.linear_model import SGDClassifier

model = SGDClassifier(random_state=42)

model.fit(X_train_new, y_train_new)

y_pred = model.predict(X_test_new)
accuracy_score(y_test_new, y_pred)

0.6317907444668008

In [77]:
from xgboost import XGBClassifier

model = XGBClassifier()

model.fit(X_train_new, y_train_new)

y_pred = model.predict(X_test_new)
accuracy_score(y_test_new, y_pred)

ModuleNotFoundError: No module named 'xgboost'

In [78]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import SGDClassifier

model = SGDClassifier(random_state=42)

scores = cross_val_score(model, X_train_new, y_train, cv=5)

print(scores)
print(scores.mean())

[0.59949622 0.68261965 0.64987406 0.64231738 0.59193955]
0.6332493702770781